export enum EMVQR {
  TAG_INIT = 0,
  TAG_CRC = 63,
  TAG_MAX = 99,
  TAG_ONETIME_PAYMENT = 2, // TODO: Alter name
  TAG_MCC = 52,
  TAG_TRANSACTION_CURRENCY = 53,
  TAG_TRANSACTION_AMOUNT = 54,
  TAG_COUNTRY_CODE = 58,
  TAG_MERCHANT_NAME = 59,
  TAG_MERCHANT_CITY = 60,
  MAI_STANDARD_FIRST = 2,
  MAI_TEMPLATE_FIRST = 26,
  MAI_TEMPLATE_LAST = 51,
  TAG_TEMPLATE_GUI = 0,
  TAG_ADDITIONAL_DATA = 62,
  TAG_AD_REF_LABEL = 5,
}
