name: Runs All Unit tests

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@HEAD

      - name: Run Tests
        run: yarn test

      - name: Run Semantic-Release
        run: yarn release
